// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionStatus } from "./ActionStatus";

/**
 * One use of a tool by the assistant.
 */
export type Action = { id: string, 
/**
 * The tool's name, e.g. `calendar_create_event`.
 */
tool: string, 
/**
 * One plain-language line saying what it does, for the approval card.
 */
summary: string, 
/**
 * The arguments the model chose (after any edit by the user).
 */
arguments: Record<string, unknown>, 
/**
 * Anything that sends, changes or deletes on the user's behalf needs approval.
 */
requires_approval: boolean, status: ActionStatus, 
/**
 * Short past-tense description once done, e.g. "read calendar".
 */
result: string | null, error: string | null, 
/**
 * What the tool returned, as given back to the model.
 */
output: unknown, 
/**
 * The model's id for this tool call, needed to replay the conversation to it.
 */
call_id: string, 
/**
 * Which model round of the reply asked for it (0-based).
 */
round: number, 
/**
 * How much of the reply's text, in Unicode characters, came before this action,
 * so clients can show it in place.
 */
content_offset: number, 
/**
 * While it waits for approval: the text of a second choice that also stops asking
 * for this person or calendar from now on (e.g. "Don't ask again for Sam"), when
 * that would make a difference.
 */
always_allow: string | null, };
