// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailSignature } from "./MailSignature";

/**
 * The signature of one of the user's addresses.
 */
export type AddressSignature = { address: string, signature: MailSignature, };
