// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of every non-2xx API response.
 */
export type ApiError = { 
/**
 * Stable, machine-readable code, e.g. `not_found`.
 */
code: string, 
/**
 * Human-readable explanation, suitable for showing to the user.
 */
message: string, };
