// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of `POST /v1/actions/{id}/approve`.
 */
export type ApproveAction = { 
/**
 * Replaces the model's arguments, when the user edited them.
 */
arguments: Record<string, unknown> | null, 
/**
 * The user chose the card's `always_allow`: approve, and add the matching exception
 * in Settings › Permissions. Not with edited arguments.
 */
always: boolean, };
