// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who approves what a trusted person asks for, when it needs approval.
 */
export type Approver = "guest" | "owner";
