// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of file is attached to a message. Only pictures for now; videos may be a
 * kind of their own. (Voice isn't kept: what's said is transcribed, see `spoken`.)
 */
export type AttachmentKind = "image";
