// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of file is attached to a message. Only pictures for now; voice notes and
 * videos will be kinds of their own.
 */
export type AttachmentKind = "image";
