// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentKind } from "./AttachmentKind";

/**
 * A file the user sent with a message, as the daemon keeps it: pictures are decoded,
 * shrunk, stripped of their metadata (location, camera…) and saved again as JPEG or
 * PNG. Its content is served at `GET /v1/attachments/{id}`.
 */
export type Attachment = { id: string, kind: AttachmentKind, 
/**
 * The content type as kept: `image/jpeg` or `image/png`.
 */
mime: string, 
/**
 * The name it came with, or a plain one ("Photo 1.jpg").
 */
name: string, 
/**
 * Bytes, as kept.
 */
size: number, 
/**
 * Pixels, for pictures.
 */
width: number | null, height: number | null, };
