// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One calendar the user can see, from any account.
 */
export type CalendarInfo = { 
/**
 * Stable across restarts; used to show, hide and add to it.
 */
id: string, name: string, 
/**
 * `#rrggbb`: the calendar's own colour when it has one, else a stable pick.
 */
color: string, 
/**
 * Events are saved straight into it. Google calendars aren't: new events open in
 * Google Calendar for the user to save.
 */
writable: boolean, google: boolean, 
/**
 * People can be invited to events saved in it (guests). False for calendars read
 * through a private address, and for CalDAV accounts Mimi has no email address for.
 */
guests: boolean, };
