// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventPerson } from "./EventPerson";

/**
 * One occurrence of an event. Titles, places and notes come from calendars, which
 * other people can write into: show them as plain text.
 */
export type CalendarEvent = { 
/**
 * Stable per occurrence; the same id @ mentions and "remind me before" use.
 */
id: string, calendar_id: string, calendar: string, title: string, start: number, end: number, all_day: boolean, location: string | null, notes: string | null, organizer: EventPerson | null, attendees: Array<EventPerson>, 
/**
 * One occurrence of a repeating event.
 */
repeats: boolean, 
/**
 * The user organizes it (or nobody does): they may change its guests and send
 * invitations. False for events someone else invited them to.
 */
mine: boolean, };
