// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalendarEvent } from "./CalendarEvent";

export type CalendarEvents = { events: Array<CalendarEvent>, 
/**
 * Calendars that couldn't be read just now, with why, in plain words.
 */
unavailable: Array<string>, };
