// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CatalogModel = { 
/**
 * Ollama tag, e.g. `qwen3:8b`.
 */
id: string, name: string, description: string, download_bytes: number, };
