// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a person can be reached. Phone numbers cover calls and SMS.
 */
export type Channel = "phone" | "email" | "telegram" | "signal" | "whatsapp" | "matrix" | "other";
