// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the user entered to connect an integration.
 */
export type ConnectionSetup = { "integration": "google_calendar", ics_url: string, } | { "integration": "caldav", server_url: string, username: string, password: string, } | { "integration": "telegram", bot_token: string, };
