// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailServers } from "./MailServers";

/**
 * What the user entered to connect an integration.
 */
export type ConnectionSetup = { "integration": "google_calendar", ics_url: string, } | { "integration": "caldav", server_url: string, username: string, password: string, } | { "integration": "telegram", bot_token: string, } | { "integration": "signal", } | { "integration": "email", email: string, password: string, 
/**
 * A preset id (`icloud`, `gmail`…); `None` picks one from the address.
 */
preset: string | null, 
/**
 * Server details for "Other"; ignored when a preset applies.
 */
servers: MailServers | null, };
