// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionStatus } from "./ConnectionStatus";

/**
 * A configured link to one of the user's accounts (a calendar, a Telegram bot, …).
 * Secrets stay in the daemon; clients only see this summary.
 */
export type Connection = { id: string, 
/**
 * The catalog id of the integration, e.g. `telegram`.
 */
integration: string, name: string, status: ConnectionStatus, 
/**
 * One plain-language line about its state, e.g. "3 calendars".
 */
detail: string, 
/**
 * Where the user should go next, when `status` is `needs_action` (e.g. the
 * Telegram link to press Start).
 */
action_url: string | null, created_at: number, };
