// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Conversation } from "./Conversation";
import type { Message } from "./Message";

export type ConversationDetail = { conversation: Conversation, messages: Array<Message>, };
