// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What happened to a new event.
 */
export type CreatedEvent = { 
/**
 * Saved into the calendar.
 */
saved: boolean, calendar: string, 
/**
 * For Google calendars: the pre-filled page where the user presses Save.
 */
open_url: string | null, };
