// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvitationOffer } from "./InvitationOffer";

/**
 * What happened to a new event.
 */
export type CreatedEvent = { 
/**
 * Saved into the calendar.
 */
saved: boolean, calendar: string, 
/**
 * For Google calendars: the pre-filled page where the user presses Save.
 */
open_url: string | null, 
/**
 * Invitations the user may send now (nothing has been emailed).
 */
invitations: Array<InvitationOffer>, 
/**
 * Something to tell the user, e.g. why the guests weren't added.
 */
note: string | null, };
