// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeliveryStatus } from "./DeliveryStatus";
import type { ScheduleKind } from "./ScheduleKind";

/**
 * One time a reminder went off or a routine ran.
 */
export type Delivery = { id: string, item_id: string, kind: ScheduleKind, title: string, 
/**
 * The time it was due.
 */
due_at: number, 
/**
 * When it actually happened.
 */
at: number, status: DeliveryStatus, detail: string | null, 
/**
 * For routines: where the result is.
 */
conversation_id: string | null, };
