// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DetectedServer = { preset_id: string, name: string, base_url: string, model_count: number, 
/**
 * A provider with this address is already configured.
 */
already_added: boolean, };
