// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevicePath } from "./DevicePath";

/**
 * A paired phone.
 */
export type Device = { id: string, 
/**
 * What the phone calls itself, e.g. "Vincent's iPhone".
 */
name: string, created_at: number, last_seen_at: number | null, 
/**
 * How it's connected right now; absent while it isn't.
 */
connection: DevicePath | null, 
/**
 * True for the phone making this request.
 */
this_device: boolean, };
