// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of `POST /v1/mail/threads/{id}/draft`.
 */
export type DraftRequest = { 
/**
 * What the reply should say, in the user's words ("say yes, but next week").
 */
instructions: string | null, };
