// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Someone to write to or invite, as the user types in an email's To or Cc or an
 * event's Guests (`GET /v1/people/emails?q=`): a person in People, by one of their
 * email addresses.
 */
export type EmailSuggestion = { person_id: string, name: string, email: string, };
