// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvitationOffer } from "./InvitationOffer";

/**
 * What happened to a changed or removed event.
 */
export type EventChanged = { 
/**
 * The occurrence's id afterwards (it changes when the event moves); None once
 * removed.
 */
event_id: string | null, 
/**
 * Messages the user may send the guests now (Mimi emailed nothing; on Google calendars
 * Google tells the guests itself, and `note` says so).
 */
invitations: Array<InvitationOffer>, 
/**
 * Something to tell the user, e.g. whom Google told, or why the guests weren't told.
 */
note: string | null, };
