// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A change the user makes to one occurrence of an event in the Calendar panel. Fields
 * left out stay as they are; an empty place or notes removes it.
 */
export type EventChange = { title: string | null, 
/**
 * Milliseconds, like `NewCalendarEvent`. Start and end go together.
 */
start: number | null, end: number | null, all_day: boolean | null, location: string | null, notes: string | null, 
/**
 * Everyone who should be a guest afterwards (email addresses). Absent: unchanged.
 */
guests: Array<string> | null, };
