// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Settings } from "./Settings";

/**
 * Pushed by the daemon to every client connected to `GET /v1/events` (WebSocket, one
 * JSON event per text frame).
 */
export type Event = { "type": "settings_changed", settings: Settings, } | { "type": "resync" };
