// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Someone on an event (organizer or guest), matched to People when possible.
 */
export type EventPerson = { 
/**
 * As the invitation names them. Written by whoever sent it.
 */
name: string | null, email: string, 
/**
 * The person in People with this address, if any.
 */
person_id: string | null, person_name: string | null, };
