// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Conversation } from "./Conversation";
import type { Message } from "./Message";
import type { ModelPull } from "./ModelPull";
import type { Provider } from "./Provider";
import type { Settings } from "./Settings";

/**
 * Pushed by the daemon to every client connected to `GET /v1/events` (WebSocket, one
 * JSON event per text frame).
 */
export type Event = { "type": "settings_changed", settings: Settings, } | { "type": "providers_changed", providers: Array<Provider>, } | { "type": "conversation_updated", conversation: Conversation, } | { "type": "conversation_deleted", id: string, } | { "type": "message_updated", message: Message, } | { "type": "message_delta", conversation_id: string, message_id: string, content: string, reasoning: string, } | { "type": "model_pull", pull: ModelPull, } | { "type": "resync" };
