// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of `POST /v1/mail/threads/{id}/flag`: flag (star) a conversation or take the
 * flag off.
 */
export type FlagThread = { flagged: boolean, };
