// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of `POST /v1/mail/threads/{id}/folders`: the user puts a conversation in a
 * folder or takes it out. Their choice is kept over the sorter's.
 */
export type FolderMembership = { folder: number, member: boolean, };
