// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `GET /v1/google/sign-in`: whether "Sign in with Google" works in this build. It needs
 * an app identity (OAuth client) compiled in or set in the environment.
 */
export type GoogleSignInInfo = { available: boolean, };
