// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A sign-in in progress: the client opens `url` in the browser, then polls
 * `GET /v1/google/sign-in/{id}` until it's done.
 */
export type GoogleSignIn = { id: string, 
/**
 * Google's consent page. It sends the browser back to this computer only.
 */
url: string, };
