// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GpuKind } from "./GpuKind";
import type { GpuVendor } from "./GpuVendor";

export type GpuInfo = { name: string, vendor: GpuVendor, kind: GpuKind, 
/**
 * Dedicated video memory, when known. Integrated GPUs share system memory.
 */
vram_bytes: number | null, };
