// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";

/**
 * Something a trusted person asked for that waits for the user's OK, because their
 * card says the user approves. Only the action: never their conversation.
 */
export type GuestApproval = { person_id: string, 
/**
 * Their name in People.
 */
name: string, action: Action, };
