// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Someone who could be invited: a person in People, by one of their addresses.
 */
export type GuestSuggestion = { person_id: string, name: string, email: string, };
