// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Channel } from "./Channel";

/**
 * One way to reach a person, and where Mimi learned it.
 */
export type Handle = { id: string, channel: Channel, 
/**
 * As the user would write it, e.g. "+41 79 123 45 67".
 */
value: string, 
/**
 * "mobile", "work"…, when the source says.
 */
label: string | null, 
/**
 * Where it comes from: a connection's id, or `None` when the user added it.
 */
source_id: string | null, 
/**
 * Plain-language source, e.g. "iCloud" or "Added by you".
 */
source_name: string, };
