// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GpuInfo } from "./GpuInfo";

export type HardwareInfo = { os: string, arch: string, cpu_name: string, cpu_cores: number, total_memory_bytes: number, available_memory_bytes: number, gpus: Array<GpuInfo>, };
