// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How capable this machine is at running models locally.
 */
export type HardwareTier = "minimal" | "light" | "standard" | "strong" | "workstation";
