// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unauthenticated liveness check. Deliberately reveals nothing beyond the version.
 */
export type Health = { version: string, };
