// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelRef } from "./ModelRef";

export type InstalledModel = { model: ModelRef, provider_name: string, size_bytes: number | null, 
/**
 * Whether it should run comfortably. Always true for models on another machine.
 */
fits: boolean, };
