// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IntegrationCategory } from "./IntegrationCategory";
import type { IntegrationStatus } from "./IntegrationStatus";

/**
 * Something Hearth can connect to on the user's behalf.
 */
export type Integration = { id: string, name: string, category: IntegrationCategory, description: string, 
/**
 * What connecting it lets Hearth do, in plain language.
 */
abilities: Array<string>, status: IntegrationStatus, };
