// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvitationGuest } from "./InvitationGuest";
import type { InvitationKind } from "./InvitationKind";

/**
 * Invitation emails Mimi can send for an event, from the user's own email account. Only
 * ever sent by the user's click, or by the assistant as Permissions allow.
 */
export type InvitationOffer = { id: string, kind: InvitationKind, event_title: string, 
/**
 * "on Friday 3 Oct, 19:00–21:00", in the computer's time zone.
 */
event_when: string, 
/**
 * Who it goes to.
 */
guests: Array<InvitationGuest>, 
/**
 * The address it's sent from; None while no email account is connected.
 */
from: string | null, 
/**
 * Why it's sent from that address, when it isn't the event's organizer.
 */
from_note: string | null, 
/**
 * When it was sent, if it was.
 */
sent_at: number | null, };
