// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of `PUT /v1/mail/jev`: the user's TypeSafe API key.
 */
export type JevKey = { api_key: string, };
