// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the database encryption key is kept.
 */
export type KeyStorage = "keychain" | "file";
