// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Autonomy } from "./Autonomy";
import type { PermissionRule } from "./PermissionRule";

/**
 * One kind's choice: what happens by default, and the exceptions to it.
 */
export type KindPermission = { autonomy: Autonomy, 
/**
 * Exceptions for particular people or calendars. The most specific wins.
 */
rules: Array<PermissionRule>, };
