// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Autonomy } from "./Autonomy";
import type { PermissionRule } from "./PermissionRule";

/**
 * One kind's choice: what happens by default, and the exceptions to it.
 */
export type KindPermission = { autonomy: Autonomy, 
/**
 * Exceptions for particular people, groups or calendars. The most specific wins.
 */
rules: Array<PermissionRule>, 
/**
 * The kind's switches the user turned on, by id (see [`PermissionKind::switches`]).
 */
switches: Array<string>, };
