// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a provider runs, and so where your conversations go when you use it.
 */
export type Locality = "device" | "network" | "cloud";
