// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A saved draft, as the Drafts view lists it (`GET /v1/mail/drafts`): an email the user
 * started here, or one found in an account's Drafts folder on the server (written in
 * another mail app). Drafts are never sent unless the user opens one and presses Send.
 */
export type MailDraftInfo = { id: string, 
/**
 * The account it belongs to, and is copied to (`None` until there is one).
 */
connection_id: string | null, subject: string, to: Array<string>, 
/**
 * The start of its text.
 */
snippet: string, 
/**
 * When it last changed (ms).
 */
updated_at: number, 
/**
 * The conversation it answers, when that conversation is here: it opens there, in
 * the reply box.
 */
reply_to: number | null, 
/**
 * How many files and pictures it carries.
 */
files: number, 
/**
 * Written in another mail app (found in the server's Drafts folder) and not changed
 * here since.
 */
from_elsewhere: boolean, };
