// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailAddress } from "./MailAddress";

export type MailMessage = { id: number, from: MailAddress, to: Array<MailAddress>, cc: Array<MailAddress>, date: number, 
/**
 * Plain text. HTML mail is converted, with hidden text removed.
 */
body: string, seen: boolean, from_me: boolean, attachments: Array<string>, 
/**
 * Contains instructions aimed at an AI assistant.
 */
suspicious: boolean, 
/**
 * Whether it has an HTML version to show as it was sent. `None` until known (mail
 * copied before Mimi kept it, found out the first time it's shown).
 */
has_html: boolean | null, };
