// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailAddress } from "./MailAddress";
import type { MailCategory } from "./MailCategory";

/**
 * One conversation, as the list shows it.
 */
export type MailThread = { id: number, connection_id: string, 
/**
 * Which of the user's addresses its latest incoming message arrived at.
 */
received_on: string | null, 
/**
 * A message in it contains instructions aimed at an AI assistant.
 */
suspicious: boolean, 
/**
 * The smart folders it's in.
 */
folders: number[], subject: string, 
/**
 * Everyone in the conversation except the user, most recent first.
 */
participants: Array<MailAddress>, last_at: number, message_count: number, unread: boolean, flagged: boolean, 
/**
 * `None` until it has been sorted.
 */
category: MailCategory | null, 
/**
 * One line written by the assistant.
 */
summary: string | null, 
/**
 * The start of the latest message.
 */
snippet: string, 
/**
 * Newsletters, notifications and other automatic mail.
 */
automated: boolean, 
/**
 * Whether the latest message was sent by the user.
 */
last_from_me: boolean, };
