// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailBatchAction } from "./MailBatchAction";

/**
 * Body of `POST /v1/mail/threads/batch`: one action on several conversations at once,
 * chosen together in the Mail panel. The user's own click, like the single actions.
 */
export type MailBatch = { ids: number[], action: MailBatchAction, };
