// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NewMailAttachment } from "./NewMailAttachment";

/**
 * A message to send, written by the user (or drafted for them).
 */
export type MailDraft = { 
/**
 * Which account sends it. Defaults to the thread's account, else the first one.
 */
connection_id: string | null, 
/**
 * Which of that account's addresses it's from: its own, or an alias mail has
 * arrived at. Defaults to the address a replied-to conversation arrived at, else
 * the account's.
 */
from: string | null, to: Array<string>, cc: Array<string>, 
/**
 * Blind copies: they get the message, and nobody else sees that they did. The
 * assistant may add them too; its emails then wait for the user's OK unless every
 * blind copy, like every other recipient, is someone the user knows.
 */
bcc: Array<string>, subject: string, body: string, 
/**
 * The conversation this answers, so it threads correctly.
 */
reply_to: number | null, 
/**
 * A message being forwarded: its attachments go along (fetched from the server).
 */
forward_of: number | null, 
/**
 * Files the user attached (or pasted), sent as they are, and files the assistant
 * attached by reference (`NewMailAttachment::source`).
 */
attachments: Array<NewMailAttachment>, 
/**
 * The message with its formatting, when the user wrote it in the editor: HTML that
 * the daemon cleans before sending, with pictures in the text as `cid:` addresses of
 * attachments that have a `content_id`. `body` is always the plain-text version, and
 * it's what models, tools, approval cards and checks read. Without it the message
 * goes as plain text.
 */
html?: string, 
/**
 * The saved draft this is (`/v1/mail/drafts/{id}`): sending it removes the draft
 * once it's queued, and taking it back (Undo, Cancel) saves it again.
 */
draft_id?: string, };
