// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A message to send, written by the user (or drafted for them).
 */
export type MailDraft = { 
/**
 * Which account sends it. Defaults to the thread's account, else the first one.
 */
connection_id: string | null, to: Array<string>, cc: Array<string>, subject: string, body: string, 
/**
 * The conversation this answers, so it threads correctly.
 */
reply_to: number | null, };
