// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MailReceivedAddress = { email: string, 
/**
 * Conversations in the inbox that arrived at it.
 */
threads: number, unread: number, };
