// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailServers } from "./MailServers";

/**
 * What Mimi worked out about a mailbox from its address alone.
 */
export type MailDiscovery = { 
/**
 * The provider's name when it's a service Mimi recognises ("Migadu", "Gmail").
 */
provider: string | null, 
/**
 * The connect dialog preset it corresponds to, if any.
 */
preset: string | null, 
/**
 * The servers to use; `None` when nothing was found and the user must enter them.
 */
servers: MailServers | null, 
/**
 * Whether this service wants an app-specific password rather than the usual one.
 */
needs_app_password: boolean, help: string | null, help_url: string | null, 
/**
 * False for services that don't let other apps read mail (e.g. no IMAP).
 */
supported: boolean, };
