// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NewMailAttachment } from "./NewMailAttachment";

/**
 * A message to send, written by the user (or drafted for them).
 */
export type MailDraft = { 
/**
 * Which account sends it. Defaults to the thread's account, else the first one.
 */
connection_id: string | null, 
/**
 * Which of that account's addresses it's from: its own, or an alias mail has
 * arrived at. Defaults to the address a replied-to conversation arrived at, else
 * the account's.
 */
from: string | null, to: Array<string>, cc: Array<string>, 
/**
 * Blind copies: they get the message, and nobody else sees that they did. Only
 * the user adds them (the assistant's tools have no Bcc).
 */
bcc: Array<string>, subject: string, body: string, 
/**
 * The conversation this answers, so it threads correctly.
 */
reply_to: number | null, 
/**
 * A message being forwarded: its attachments go along (fetched from the server).
 */
forward_of: number | null, 
/**
 * Files the user attached (or pasted), sent as they are.
 */
attachments: Array<NewMailAttachment>, };
