// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddressSignature } from "./AddressSignature";
import type { MailSignature } from "./MailSignature";

/**
 * The user's email signatures (Settings › General › Signature), `GET|PUT
 * /v1/mail/signatures`. A signature goes at the end of each email the user writes (below
 * their text, above anything forwarded), after a `-- ` line, and the emails the assistant
 * writes for them get it too. It's part of the draft: the user can change or delete it
 * in any one email.
 */
export type MailSignatures = { 
/**
 * Every address signs with `all`. Off: an address in `addresses` signs with its own,
 * and any other with `all`.
 */
same_for_all: boolean, all: MailSignature, 
/**
 * Signatures of single addresses (the account's own, or an alias), lowercase.
 */
addresses: Array<AddressSignature>, 
/**
 * Whether replies and forwards get it too. Some people leave it out of replies, as
 * some mail apps do.
 */
in_replies: boolean, };
