// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One email ready to show: as it was sent (its HTML, made safe) and as formatted text.
 * See `mail::render` in the daemon.
 */
export type MailContent = { 
/**
 * The email's own HTML, made safe: no scripts, forms, hidden text or anything loaded
 * from elsewhere. Pictures on other servers are left out unless `images_loaded`.
 * `None` when it has no HTML version (or it couldn't be fetched).
 */
html: string | null, 
/**
 * Markdown made from the HTML, or from the plain text: headings, emphasis, lists,
 * links, quotes and simple tables. No raw HTML, no pictures.
 */
formatted: string, 
/**
 * How many pictures in `html` come from other servers.
 */
remote_images: number, 
/**
 * Whether those pictures are in `html` (fetched by the daemon when the user asked).
 */
images_loaded: boolean, };
