// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of `POST /v1/mail/folders`, and of `PATCH` (fields left out stay as they are).
 */
export type MailFolderInput = { name: string | null, description: string | null, };
