// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailUnsubscribeMethod } from "./MailUnsubscribeMethod";
import type { MailUnsubscribed } from "./MailUnsubscribed";

/**
 * `GET /v1/mail/threads/{id}/unsubscribe`: how to unsubscribe from the list a
 * conversation's latest message came from (`null` when it doesn't say).
 */
export type MailUnsubscribe = { method: MailUnsubscribeMethod, 
/**
 * Who is asked: the domain of the web or email address ("example.com").
 */
domain: string, 
/**
 * The sender's name, else their address, for "Archive all from …".
 */
sender: string, 
/**
 * `website` only: the page to open in the browser.
 */
url: string | null, 
/**
 * Set once the user unsubscribed from this list (remembered per list).
 */
done: MailUnsubscribed | null, 
/**
 * Conversations from this list still in the Inbox, this one included.
 */
in_inbox: number, };
