// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NewMailAttachment } from "./NewMailAttachment";

/**
 * One signature, written in the mail editor: like a draft's text, a plain-text version
 * and, with formatting, HTML whose pictures are `cid:` addresses of `pictures`.
 */
export type MailSignature = { 
/**
 * The plain text, one line per line (a picture reads "[image: name]"). Empty: none.
 */
text: string, 
/**
 * With its formatting, cleaned like the HTML of an email when saved. `None`: plain.
 */
html?: string, 
/**
 * Small pictures in it (a logo), kept with the setting and sent in the email's text.
 * Each has a `content_id` and its data; at most a few, small (see `mail::signature`).
 */
pictures: Array<NewMailAttachment>, };
