// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NewMailNotify } from "./NewMailNotify";

/**
 * Notifications on this computer when new mail lands in an Inbox (`mail::notify`).
 */
export type MailNotifications = { notify: NewMailNotify, 
/**
 * Whether a notification says who wrote and the subject. Off: only "New email", for
 * screens others can see (a lock screen). Suspicious mail never shows its subject.
 */
show_details: boolean, };
