// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailReceivedAddress } from "./MailReceivedAddress";

export type MailAccount = { connection_id: string, email: string, name: string, 
/**
 * The addresses its inbox mail arrived at (aliases, catch-all addresses, +tags),
 * the account's own first.
 */
addresses: Array<MailReceivedAddress>, };
