// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of `POST /v1/mail/older`: look on the mail servers for mail older than what's
 * kept here (the last 90 days).
 */
export type MailOlderSearch = { 
/**
 * Words to look for, as in the search field.
 */
q: string, 
/**
 * Only this account's server (every account's when missing).
 */
account: string | null, };
