// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailServers } from "./MailServers";

/**
 * A mail service the user can pick when connecting.
 */
export type MailPreset = { id: string, name: string, 
/**
 * How to get the app password, in plain language.
 */
help: string, help_url: string | null, 
/**
 * `None` means the user types the server details ("Other").
 */
servers: MailServers | null, 
/**
 * False for services that need a sign-in Mimi doesn't support yet.
 */
supported: boolean, };
