// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A file the assistant attached to an email by reference, fetched only when it's sent.
 * Never a file from the computer: only these.
 */
export type MailAttachmentSource = { "kind": "email", 
/**
 * The message (`MailMessage.id`).
 */
message: number, 
/**
 * Which of its attachments, in the order `MailMessage.attachments` lists them.
 */
index: number, 
/**
 * Its size in bytes when it was attached, for showing.
 */
size: number | null, } | { "kind": "chat", attachment: string, 
/**
 * Its size in bytes, for showing.
 */
size: number | null, };
