// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailBatchFailure } from "./MailBatchFailure";

/**
 * Answer of `POST /v1/mail/threads/batch`. Some conversations can fail while others
 * work (one account's server can't be reached): `failed` says which, and `message` says
 * so in plain words.
 */
export type MailBatchResult = { 
/**
 * Conversations it was done to (or that needed nothing).
 */
done: number[], failed: Array<MailBatchFailure>, 
/**
 * What went wrong, for showing as it is; `None` when nothing did.
 */
message: string | null, };
