// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailMessage } from "./MailMessage";
import type { MailThread } from "./MailThread";

export type MailThreadDetail = { thread: MailThread, messages: Array<MailMessage>, };
