// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Locality } from "./Locality";
import type { MailAccount } from "./MailAccount";
import type { MailFolder } from "./MailFolder";
import type { MailSorter } from "./MailSorter";

/**
 * Counts for the sidebar (for the whole mail, or the account or address asked for),
 * plus the connected accounts.
 */
export type MailOverview = { accounts: Array<MailAccount>, needs_reply: number, important: number, unread: number, 
/**
 * Whether new mail is sorted in the background.
 */
sorting: boolean, 
/**
 * Where the model that sorts, summarises and drafts runs; `None` without one.
 */
model_locality: Locality | null, 
/**
 * What sorts new mail (`Settings.mail_sorter`), and where that runs.
 */
sorter: MailSorter, sorter_locality: Locality | null, 
/**
 * Whether a TypeSafe key is saved, so Jev can be chosen.
 */
jev_connected: boolean, 
/**
 * The user's smart folders.
 */
folders: Array<MailFolder>, };
