// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Conversations a batch couldn't change, and why.
 */
export type MailBatchFailure = { ids: number[], reason: string, };
