// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Answer of `POST /v1/mail/threads/{id}/unsubscribe/archive`.
 */
export type MailArchivedCount = { archived: number, };
