// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What part of the mail to show.
 */
export type MailBox = "needs_reply" | "important" | "other" | "inbox" | "sent" | "archive" | "flagged";
