// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a batch does to each conversation.
 */
export type MailBatchAction = { "kind": "archive" } | { "kind": "delete" } | { "kind": "read", read: boolean, } | { "kind": "flag", flagged: boolean, } | { "kind": "folder", folder: number, member: boolean, };
