// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailThread } from "./MailThread";

/**
 * What a search of the mail servers found, older than what's kept here.
 */
export type MailOlderResults = { 
/**
 * Conversations with a match, newest first. They're kept here for a while (a week,
 * or 30 days after they were last opened) and open like any other.
 */
threads: Array<MailThread>, 
/**
 * The servers were searched for mail from before this moment.
 */
before: number, 
/**
 * More matched than were brought in: only the newest are.
 */
more: boolean, 
/**
 * Accounts that couldn't be searched, or only partly, in plain words.
 */
problems: Array<string>, };
