// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A smart folder: the user's sorter files conversations that fit its description.
 */
export type MailFolder = { id: number, name: string, 
/**
 * What goes in it, in the user's words.
 */
description: string, 
/**
 * How it looks: an icon and a colour, by name (see `MailFolderInput`).
 */
icon: string, color: string, 
/**
 * Conversations in it, and how many of those are unread.
 */
threads: number, unread: number, 
/**
 * Conversations not yet checked against it (it's still being filled).
 */
to_check: number, };
