// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailUnsubscribeMethod } from "./MailUnsubscribeMethod";

export type MailUnsubscribed = { method: MailUnsubscribeMethod, at: number, };
