// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailSecurity } from "./MailSecurity";

/**
 * Where an account's mail lives.
 */
export type MailServers = { imap_host: string, imap_port: number, imap_security: MailSecurity, smtp_host: string, smtp_port: number, smtp_security: MailSecurity, 
/**
 * Login name, when it isn't the email address.
 */
username: string | null, };
