// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailAddress } from "./MailAddress";

export type MailMessage = { id: number, from: MailAddress, to: Array<MailAddress>, cc: Array<MailAddress>, date: number, 
/**
 * Plain text. HTML mail is converted, with hidden text removed.
 */
body: string, seen: boolean, from_me: boolean, attachments: Array<string>, };
