// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a mail server connection is protected.
 */
export type MailSecurity = "tls" | "start_tls" | "plain";
