// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of `POST /v1/mail/threads/{id}/read`.
 */
export type MarkRead = { read: boolean, };
