// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Matrix group the assistant is in (`GET /v1/matrix/groups`), e.g. for an exception
 * in Settings › Permissions. The name is whatever the group's members called it.
 */
export type MatrixGroup = { 
/**
 * The room id, `!…`.
 */
id: string, name: string, 
/**
 * Its address, `#name:server`, when it has one.
 */
alias: string | null, members: number, };
