// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemorySource } from "./MemorySource";

/**
 * One note in the memory library, e.g. `people/sam.md`.
 */
export type MemoryNote = { 
/**
 * Where it lives: `folder/name.md`, lowercase.
 */
path: string, title: string, 
/**
 * Markdown, usually a short list of facts.
 */
body: string, 
/**
 * Optional link to something the note is about, e.g. a contact's id. Unused for now.
 */
subject: string | null, source: MemorySource, created_at: number, updated_at: number, };
