// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemorySource } from "./MemorySource";

/**
 * A note without its body, for listing.
 */
export type MemoryNoteSummary = { path: string, title: string, 
/**
 * The first line or so of the body.
 */
preview: string, source: MemorySource, updated_at: number, };
