// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemorySource } from "./MemorySource";

/**
 * One note in the memory library, e.g. `people/sam.md`.
 */
export type MemoryNote = { 
/**
 * Where it lives: `folder/name.md`, lowercase.
 */
path: string, title: string, 
/**
 * Markdown, usually a short list of facts.
 */
body: string, 
/**
 * The person in the people directory this note is about, by id, if known.
 */
subject: string | null, 
/**
 * That person's name, for showing the link.
 */
subject_name: string | null, source: MemorySource, created_at: number, updated_at: number, };
