// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who last wrote a memory note.
 */
export type MemorySource = "you" | "assistant" | "learned";
