// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryNoteSummary } from "./MemoryNoteSummary";
import type { MemorySemantic } from "./MemorySemantic";

/**
 * Everything the Memory screen shows.
 */
export type MemoryOverview = { 
/**
 * The short summary that's always given to the assistant.
 */
profile: string, 
/**
 * Most characters the profile may hold.
 */
profile_limit: number, notes: Array<MemoryNoteSummary>, 
/**
 * Whether the assistant learns from conversations. Paused means nothing new is
 * remembered; what's known is still used.
 */
learning: boolean, 
/**
 * Finding memories by meaning.
 */
semantic: MemorySemantic, };
