// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether memories are found by meaning as well as by their words, and what that
 * needs. The language file behind it is a small embedding model that runs on this
 * computer (or in the user's Ollama); nothing leaves the machine.
 */
export type MemorySemantic = { 
/**
 * The user's choice.
 */
enabled: boolean, 
/**
 * Whether this computer can do it: Mimi's built-in model runtime, or Ollama.
 */
available: boolean, 
/**
 * Whether the language file is on this computer.
 */
installed: boolean, 
/**
 * Size of the one-time download.
 */
download_bytes: number, 
/**
 * The download to watch in `ModelPull` events, as source and model id.
 */
provider_id: string | null, model: string, 
/**
 * Notes understood so far, out of all notes.
 */
indexed: number, total: number, 
/**
 * What went wrong last, in plain language.
 */
error: string | null, };
