// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MentionKind } from "./MentionKind";

/**
 * Something the user tagged with @ in a message.
 */
export type Mention = { kind: MentionKind, 
/**
 * A person's id, or an event's id from the mention search.
 */
id: string, 
/**
 * The text shown after the @, e.g. "Sam Carter".
 */
label: string, };
