// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Channel } from "./Channel";
import type { MentionKind } from "./MentionKind";

/**
 * A suggestion in the @ picker.
 */
export type MentionCandidate = { kind: MentionKind, id: string, label: string, 
/**
 * One quiet line: an event's day and time and calendar, a nickname…
 */
detail: string | null, 
/**
 * For people: how they can be reached.
 */
channels: Array<Channel>, 
/**
 * For events: when they start (ms since the epoch).
 */
starts_at: number | null, };
