// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MentionKind } from "./MentionKind";

/**
 * Something the user tagged with @ (people, events) or # (email) in a message.
 */
export type Mention = { kind: MentionKind, 
/**
 * A person's id, an event's id from the mention search, or an email
 * conversation's or message's number.
 */
id: string, 
/**
 * The text shown after the @ or #, e.g. "Sam Carter".
 */
label: string, };
