// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Person } from "./Person";

/**
 * A merge that happened.
 */
export type MergeResult = { person: Person, 
/**
 * Undoes it exactly, while nothing has come to depend on it:
 * `POST /people/merges/{merge_id}/undo`.
 */
merge_id: string, };
