// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The user's choice to merge people (`POST /people/merge`; `POST
 * /people/merge/preview` shows the result first). Never automatic: contacts only
 * unify on their own through a shared number, address or username.
 */
export type MergeRequest = { 
/**
 * Whose id stays. Old links to the others find this person.
 */
keep: string, 
/**
 * Folded into `keep`, then gone.
 */
others: Array<string>, 
/**
 * The merged person's name; `None` keeps `keep`'s.
 */
name: string | null, };
