// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Handle } from "./Handle";
import type { PersonSummary } from "./PersonSummary";

/**
 * What a merge would give, for the confirmation.
 */
export type MergePreview = { 
/**
 * Everyone being merged, `keep` first.
 */
people: Array<PersonSummary>, 
/**
 * Their different names, `keep`'s first: the names to choose from.
 */
names: Array<string>, 
/**
 * Every way to reach the merged person; the same number or address counts once.
 */
handles: Array<Handle>, };
