// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MergePeople = { 
/**
 * Folded into the person in the URL, then removed.
 */
other: string, };
