// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /people/{id}/merge`: one person into another. `POST /people/merge` takes
 * several at once, and a name.
 */
export type MergePeople = { 
/**
 * Folded into the person in the URL, then removed.
 */
other: string, };
