// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Locality } from "./Locality";
import type { MessageRole } from "./MessageRole";
import type { MessageStatus } from "./MessageStatus";
import type { ModelRef } from "./ModelRef";

export type Message = { id: string, conversation_id: string, role: MessageRole, content: string, 
/**
 * A reasoning model's thinking, kept apart from the answer. Empty if none.
 */
reasoning: string, status: MessageStatus, 
/**
 * The model that wrote an assistant message.
 */
model: ModelRef | null, 
/**
 * Where that model ran, as it was when the message was written.
 */
locality: Locality | null, error: string | null, created_at: number, };
