// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { Attachment } from "./Attachment";
import type { Locality } from "./Locality";
import type { Mention } from "./Mention";
import type { MessageRole } from "./MessageRole";
import type { MessageStatus } from "./MessageStatus";
import type { ModelRef } from "./ModelRef";

export type Message = { id: string, conversation_id: string, role: MessageRole, content: string, 
/**
 * A reasoning model's thinking, kept apart from the answer. Empty if none.
 */
reasoning: string, status: MessageStatus, 
/**
 * The model that wrote an assistant message.
 */
model: ModelRef | null, 
/**
 * Where that model ran, as it was when the message was written.
 */
locality: Locality | null, error: string | null, created_at: number, 
/**
 * Tools the assistant used, or asked permission to use, while writing this reply.
 */
actions: Array<Action>, 
/**
 * People and events the user tagged with @ in this message.
 */
mentions: Array<Mention>, 
/**
 * Photos the user sent with this message (only user messages have them).
 */
attachments: Array<Attachment>, 
/**
 * The model this message went to couldn't see its photos, so it was only told that
 * the user sent some. Clients say so under the message.
 */
attachments_unseen: boolean, };
