// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PullState } from "./PullState";

/**
 * Progress of a model download through a model source that supports it (Ollama).
 */
export type ModelPull = { provider_id: string, model: string, state: PullState, 
/**
 * The source's own description of the current step.
 */
status: string, completed_bytes: number | null, total_bytes: number | null, error: string | null, };
