// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelInfo = { id: string, 
/**
 * On-disk size, when the provider reports it (Ollama does).
 */
size_bytes: number | null, };
