// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A cloud model's price, in US dollars per million tokens.
 */
export type ModelPrice = { input: number, output: number, };
