// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelPrice } from "./ModelPrice";

export type ModelInfo = { id: string, 
/**
 * The provider's own name for the model (e.g. "Claude Sonnet 5"), when it has one.
 */
name: string | null, 
/**
 * On-disk size, when the provider reports it (Ollama does).
 */
size_bytes: number | null, 
/**
 * Whether the model can use tools (calendar, mail, reminders…), when the provider
 * says (OpenRouter and Anthropic do).
 */
supports_tools: boolean | null, 
/**
 * What the provider charges, when it publishes prices (OpenRouter does).
 */
price: ModelPrice | null, };
