// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A file sent with a new message.
 */
export type NewAttachment = { 
/**
 * The file's content, base64-encoded (standard alphabet, padding optional).
 */
data: string, 
/**
 * Its file name, if it has one.
 */
name: string | null, 
/**
 * The content type the client believes it has. Only a hint: the daemon reads the
 * file itself and refuses what isn't a picture.
 */
mime: string | null, };
