// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An event the user adds from the Calendar panel.
 */
export type NewCalendarEvent = { calendar_id: string, title: string, 
/**
 * Milliseconds; for all-day events, local midnight of the first day.
 */
start: number, 
/**
 * Milliseconds; for all-day events, local midnight after the last day.
 */
end: number, all_day: boolean, location: string | null, notes: string | null, 
/**
 * People to invite: email addresses ("Sam <sam@example.com>" or bare). The calendar
 * service emails nobody; the answer offers to send the invitations.
 */
guests: Array<string>, };
