// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A file the user attaches to an email they write.
 */
export type NewMailAttachment = { name: string, 
/**
 * Its content type as the app read it, e.g. "application/pdf". Unknown or
 * unreadable types go as "application/octet-stream".
 */
mime: string | null, 
/**
 * The file's content, base64-encoded.
 */
data: string, };
