// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailAttachmentSource } from "./MailAttachmentSource";

/**
 * A file the user attaches to an email they write.
 */
export type NewMailAttachment = { name: string, 
/**
 * Its content type as the app read it, e.g. "application/pdf". Unknown or
 * unreadable types go as "application/octet-stream".
 */
mime: string | null, 
/**
 * The file's content, base64-encoded. Empty when `source` says where it is.
 */
data: string, 
/**
 * Where the file is, when the assistant attached it: the daemon fetches it when
 * the email is sent, so the model never handles the file itself.
 */
source: MailAttachmentSource | null, 
/**
 * Set for a picture placed in the text: the `html` shows it as `cid:<content_id>`.
 */
content_id?: string, };
