// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailDraft } from "./MailDraft";

/**
 * Body of `POST /v1/mail/outbox`: the user's Send, or Send later.
 */
export type NewOutgoingMail = { draft: MailDraft, 
/**
 * When to send it (ms since the epoch). `None`: now, after the few seconds Undo is
 * offered (`Settings.undo_send_secs`; straight away when that's off).
 */
send_at: number | null, };
