// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Locality } from "./Locality";
import type { ProviderKind } from "./ProviderKind";

export type NewProvider = { name: string, kind: ProviderKind, base_url: string, api_key: string | null, 
/**
 * Derived from `base_url` when omitted.
 */
locality: Locality | null, };
