// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NewHandle } from "./NewHandle";

export type NewPerson = { name: string, nickname: string | null, handles: Array<NewHandle>, };
