// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Schedule } from "./Schedule";
import type { ScheduleKind } from "./ScheduleKind";

export type NewScheduleItem = { kind: ScheduleKind, title: string, instruction: string | null, schedule: Schedule, };
