// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a message waits in the outbox.
 */
export type OutgoingKind = "undo" | "scheduled";
