// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailDraft } from "./MailDraft";
import type { OutgoingKind } from "./OutgoingKind";
import type { OutgoingStatus } from "./OutgoingStatus";

/**
 * A message in the outbox. Lists and events leave the attachments' content out
 * (`data` is empty); cancelling one gives the whole draft back.
 */
export type OutgoingMail = { id: string, kind: OutgoingKind, status: OutgoingStatus, 
/**
 * The draft as the user wrote it.
 */
draft: MailDraft, 
/**
 * The account it goes from, and the address.
 */
connection_id: string, from: string, 
/**
 * When it goes (ms). For a late one, when it was due.
 */
send_at: number, created_at: number, 
/**
 * When it actually went, for `sent`: later than `send_at` when the computer was
 * off or asleep at that time.
 */
sent_at: number | null, 
/**
 * What went wrong, in plain words.
 */
error: string | null, 
/**
 * Scheduled by the assistant, with the user's OK.
 */
by_assistant: boolean, };
