// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Device } from "./Device";

/**
 * The phone's credentials: keep the token in the Keychain and send it as
 * `Authorization: Bearer <token>` on every request over this connection.
 */
export type Paired = { device: Device, token: string, };
