// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A one-time pairing code, shown as a QR code for the phone to scan.
 */
export type PairingOffer = { 
/**
 * `mimi://pair?id=<endpoint id>&code=<code>[&relay=<url>]`: what the QR code holds.
 */
link: string, 
/**
 * The QR code, as an SVG document.
 */
qr_svg: string, expires_at: number, };
