// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sent by a phone over its first connection, with the code from the QR code.
 */
export type PairRequest = { code: string, name: string, };
