// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an exception is about.
 */
export type PermissionTarget = { "kind": "person", "id": string } | { "kind": "calendar", "id": string } | { "kind": "matrix_room", "id": string };
