// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KindPermission } from "./KindPermission";

/**
 * The user's choices, by kind id (`send_mail`, `add_events`…). A kind that isn't
 * listed uses its default. Changed only through `PUT /v1/permissions/{kind}` (and the
 * "don't ask again" choice on an approval card): never by the assistant.
 *
 * Settings saved before exceptions existed (`{"send_mail": "automatic", …}`) still load
 * with the same meaning.
 */
export type Permissions = { [key in string]: KindPermission };
