// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a kind's exceptions can be about.
 */
export type PermissionTargetKind = "none" | "person" | "calendar";
