// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Autonomy } from "./Autonomy";
import type { PermissionTarget } from "./PermissionTarget";

/**
 * An exception: this person, group or calendar gets `autonomy` instead of the default.
 */
export type PermissionRule = { target: PermissionTarget, autonomy: Autonomy, };
