// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Autonomy } from "./Autonomy";
import type { PermissionTarget } from "./PermissionTarget";

/**
 * An exception as clients show it.
 */
export type PermissionRuleView = { target: PermissionTarget, autonomy: Autonomy, 
/**
 * The person's, group's or calendar's name.
 */
label: string, 
/**
 * The person, group or calendar is gone; the exception does nothing.
 */
missing: boolean, };
