// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An extra choice a kind offers, e.g. "Everyone on example.org counts as someone you
 * know". Turned on by listing its id in [`KindPermission::switches`].
 */
export type PermissionSwitch = { id: string, title: string, 
/**
 * Why it's off unless the user chooses it, in one or two plain sentences.
 */
detail: string, on: boolean, };
