// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Autonomy } from "./Autonomy";
import type { PermissionRuleView } from "./PermissionRuleView";
import type { PermissionSwitch } from "./PermissionSwitch";
import type { PermissionTargetKind } from "./PermissionTargetKind";

/**
 * A kind of action, as `GET /v1/permissions` serves it: how to show it, and the user's
 * current choice.
 */
export type PermissionKind = { 
/**
 * Stable, e.g. `send_mail`.
 */
id: string, 
/**
 * "Send emails".
 */
title: string, 
/**
 * What asking first means for this kind, one plain sentence.
 */
ask_detail: string, 
/**
 * What automatic means, one plain sentence.
 */
automatic_detail: string, 
/**
 * A safety net that holds whatever the choice, in one plain sentence.
 */
note: string | null, 
/**
 * A lucide icon name, e.g. `send`.
 */
icon: string, 
/**
 * `#rrggbb` for the icon tile.
 */
color: string, default_autonomy: Autonomy, targets: PermissionTargetKind, 
/**
 * The user's choice for everything without an exception.
 */
autonomy: Autonomy, rules: Array<PermissionRuleView>, 
/**
 * Extra choices, shown as switches under the kind.
 */
switches: Array<PermissionSwitch>, };
