// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Autonomy } from "./Autonomy";

/**
 * What the assistant may do on its own, per kind of action (Settings › Permissions).
 * Anything not listed here keeps its own rule: reads never ask, and every other action
 * that sends or changes something always does.
 */
export type Permissions = { 
/**
 * Sending email. Automatic still asks before writing to anyone the user doesn't
 * know (not in their contacts, never emailed): a hostile email can't make the
 * assistant mail a stranger.
 */
send_mail: Autonomy, 
/**
 * Adding events to the user's own calendars.
 */
add_events: Autonomy, 
/**
 * Setting, changing and cancelling reminders and routines.
 */
schedule: Autonomy, };
