// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Channel } from "./Channel";

/**
 * A person in lists and pickers.
 */
export type PersonSummary = { id: string, name: string, nickname: string | null, 
/**
 * Distinct channels, in a stable order.
 */
channels: Array<Channel>, };
