// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fields left `null` are unchanged; an empty nickname clears it.
 */
export type PersonUpdate = { name: string | null, nickname: string | null, };
