// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Handle } from "./Handle";
import type { PersonSource } from "./PersonSource";

export type Person = { id: string, name: string, nickname: string | null, handles: Array<Handle>, 
/**
 * The cards merged into this person. Several means it was unified.
 */
sources: Array<PersonSource>, 
/**
 * Added by the user rather than imported. (People merged into them become cards
 * in `sources` instead.)
 */
manual: boolean, };
