// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Approver } from "./Approver";

/**
 * What someone in People may do with the assistant (`GET /people/{id}/access`).
 */
export type PersonAccess = { person_id: string, 
/**
 * They may ask the assistant things. Off for everyone until the user turns it on.
 */
enabled: boolean, 
/**
 * The calendars shared with them (`GET /calendars` ids): the only ones the
 * assistant reads or writes for them.
 */
calendars: Array<string>, approver: Approver, 
/**
 * The addresses they can write from: their Matrix addresses from an address book
 * or added by hand (never one Mimi only saw in mail).
 */
addresses: Array<string>, 
/**
 * The assistant's own Matrix accounts they can write to.
 */
assistant_addresses: Array<string>, };
