// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A conversation where the user @-mentioned someone.
 */
export type PersonConversation = { id: string, title: string, updated_at: number, };
