// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A contact card attached to a person: from a source, or what the user had added by
 * hand to someone they later merged into this person. Each can be separated again
 * ("Not the same person", `POST /people/{id}/split`).
 */
export type PersonSource = { 
/**
 * The connection the card comes from, or `None` for what the user added by hand.
 */
source_id: string | null, source_name: string, 
/**
 * The card's id within its source; for what the user added, the id that contact
 * had before the merge.
 */
record: string, 
/**
 * The name on that card.
 */
name: string, };
