// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A contact card from a source, attached to a person.
 */
export type PersonSource = { source_id: string, source_name: string, 
/**
 * The card's id within its source.
 */
record: string, 
/**
 * The name on that card.
 */
name: string, };
