// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Approver } from "./Approver";

/**
 * A change to someone's access (`PUT /people/{id}/access`); what's left out stays.
 */
export type PersonAccessUpdate = { enabled?: boolean, calendars?: Array<string>, approver?: Approver, };
