// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderKind } from "./ProviderKind";

/**
 * Checks a provider's connection details before saving them.
 */
export type ProbeRequest = { kind: ProviderKind, base_url: string, api_key: string | null, };
