// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Locality } from "./Locality";
import type { ModelInfo } from "./ModelInfo";

export type ProbeResult = { 
/**
 * The address that worked. May differ from the request, e.g. with `/v1` added.
 */
base_url: string, locality: Locality, models: Array<ModelInfo>, };
