// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Locality } from "./Locality";
import type { ProviderKind } from "./ProviderKind";

/**
 * A well-known provider the user can add with one click.
 */
export type ProviderPreset = { id: string, name: string, description: string, kind: ProviderKind, base_url: string, locality: Locality, needs_api_key: boolean, 
/**
 * The service's page for creating an API key, for a "Get a key" button.
 */
key_url: string | null, 
/**
 * The model to suggest once connected, when the service offers it.
 */
recommended_model: string | null, };
