// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Locality } from "./Locality";
import type { ProviderKind } from "./ProviderKind";

export type Provider = { id: string, name: string, kind: ProviderKind, base_url: string, locality: Locality, 
/**
 * API keys are write-only: clients only learn whether one is set.
 */
has_api_key: boolean, created_at: number, };
