// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Locality } from "./Locality";

/**
 * Fields left `null` are unchanged. An empty `api_key` removes the stored key.
 */
export type ProviderUpdate = { name: string | null, base_url: string | null, api_key: string | null, locality: Locality | null, };
