// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Locality } from "./Locality";

/**
 * A well-known provider the user can add with one click.
 */
export type ProviderPreset = { id: string, name: string, description: string, base_url: string, locality: Locality, needs_api_key: boolean, };
