// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogModel } from "./CatalogModel";
import type { DetectedServer } from "./DetectedServer";
import type { HardwareInfo } from "./HardwareInfo";
import type { HardwareTier } from "./HardwareTier";
import type { InstalledModel } from "./InstalledModel";

export type Recommendations = { hardware: HardwareInfo, tier: HardwareTier, 
/**
 * Roughly how large a model (weights plus working memory) runs comfortably here.
 */
model_budget_bytes: number, 
/**
 * Plain-language explanation of what this machine can do.
 */
summary: string, 
/**
 * Whether a cloud model is the better default on this machine.
 */
prefer_cloud: boolean, 
/**
 * Models already available from private providers, best first.
 */
installed: Array<InstalledModel>, 
/**
 * Models worth downloading for this machine, best first.
 */
suggested: Array<CatalogModel>, 
/**
 * Local model servers found running on this computer.
 */
detected_servers: Array<DetectedServer>, };
