// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which relay helps phones reach this computer when a direct connection isn't possible.
 */
export type Relay = { "kind": "default" } | { "kind": "custom", url: string, };
