// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A published version.
 */
export type Release = { 
/**
 * e.g. "0.2.0".
 */
version: string, 
/**
 * Its release page (what's new, and the downloads).
 */
url: string, };
