// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Device } from "./Device";
import type { Relay } from "./Relay";

/**
 * Using Mimi from a phone (Settings › Phone): the phones paired with this computer and
 * how they reach it. Phones connect peer to peer (iroh), straight to this computer when
 * they can, else through a relay that passes on encrypted traffic it can't read.
 */
export type RemoteAccess = { 
/**
 * True while phones can reach this computer: once one is paired, or while a pairing
 * code is waiting to be scanned.
 */
running: boolean, 
/**
 * This computer's address for phones, which is also its public key: a phone checks
 * it's talking to this computer and nothing else. Absent until first started.
 */
endpoint_id: string | null, relay: Relay, 
/**
 * Whether this computer is reachable through its relay right now, so phones on
 * other networks can find it.
 */
relay_connected: boolean, devices: Array<Device>, 
/**
 * Why phones can't reach this computer, in plain words.
 */
error: string | null, };
