// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Someone the user deleted from Mimi (not from their address book), who can be
 * brought back. `DELETE /people/{id}` returns this, or `null` when nothing is left to
 * bring back (someone the user had added themselves).
 */
export type RemovedPerson = { 
/**
 * The id they had, and get back when restored.
 */
id: string, name: string, nickname: string | null, 
/**
 * When they were deleted (ms since the epoch).
 */
removed_at: number, 
/**
 * Plain-language names of where their cards come from, e.g. "iCloud".
 */
sources: Array<string>, };
