// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of `PATCH /v1/mail/outbox/{id}`: send it at another time.
 */
export type RescheduleMail = { send_at: number, };
