// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeState } from "./RuntimeState";

/**
 * The built-in model runtime.
 */
export type RuntimeStatus = { 
/**
 * Whether this installation includes the runtime.
 */
available: boolean, state: RuntimeState, 
/**
 * The model currently loaded, if any.
 */
model: string | null, 
/**
 * Why it last failed to start, in plain language.
 */
error: string | null, 
/**
 * Space used by downloaded models.
 */
models_bytes: number, };
