// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailDraft } from "./MailDraft";

/**
 * Body of `PUT /v1/mail/drafts/{id}`: the draft as it is now, saved as the user writes.
 */
export type SaveMailDraft = { draft: MailDraft, 
/**
 * The editor closed: copy it to the server's Drafts folder now rather than after a
 * pause.
 */
now: boolean, };
