// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Schedule } from "./Schedule";
import type { ScheduleKind } from "./ScheduleKind";

export type ScheduleItem = { id: string, kind: ScheduleKind, 
/**
 * What to remind about, or the routine's name.
 */
title: string, 
/**
 * For routines: what the assistant does each time.
 */
instruction: string | null, schedule: Schedule, 
/**
 * The schedule in words, e.g. "Every weekday at 07:00".
 */
description: string, paused: boolean, 
/**
 * When it happens next, if ever. Includes snoozes.
 */
next_at: number | null, last_at: number | null, 
/**
 * Why it won't happen again, e.g. "The event was cancelled". `None` while active.
 */
ended: string | null, 
/**
 * For routines: the conversation their results go to.
 */
conversation_id: string | null, created_at: number, };
