// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Weekday } from "./Weekday";

/**
 * When something happens. Stored as a rule, not as instants, so times stay right
 * across daylight-saving changes and follow the computer's time zone. Times are
 * local, `HH:MM`; dates are local, `YYYY-MM-DD`.
 */
export type Schedule = { "type": "once", at: string, } | { "type": "daily", time: string, } | { "type": "weekdays", time: string, } | { "type": "weekly", days: Array<Weekday>, time: string, } | { "type": "monthly", day: number, time: string, } | { "type": "yearly", month: number, day: number, time: string, } | { "type": "interval", minutes: number, } | { "type": "before_event", 
/**
 * An event id as used by @ mentions (`ev:…`).
 */
event_id: string, event_title: string, minutes_before: number, };
