// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Schedule } from "./Schedule";

/**
 * Fields left `null` are unchanged.
 */
export type ScheduleUpdate = { title: string | null, instruction: string | null, schedule: Schedule | null, paused: boolean | null, };
