// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeliveryStatus } from "./DeliveryStatus";

/**
 * One time a reminder or routine goes off (or went off), for showing it in a calendar.
 * Items that repeat every few minutes come once per day, standing for `count` times
 * from `at` to `until`.
 */
export type ScheduleOccurrence = { item_id: string, 
/**
 * When it's due (the first of them, when several are folded into one).
 */
at: number, 
/**
 * The last of them; the same as `at` for a single one.
 */
until: number, count: number, 
/**
 * What happened, for one that already came due (from the history); empty for one
 * still to come.
 */
status: DeliveryStatus | null, 
/**
 * When a snoozed reminder comes back, rather than a time from its schedule.
 */
snoozed: boolean, };
