// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Mention } from "./Mention";
import type { ModelRef } from "./ModelRef";

export type SendMessage = { content: string, 
/**
 * Overrides the default model for this reply.
 */
model: ModelRef | null, 
/**
 * People and events tagged with @. Each label appears in `content` as `@label`.
 */
mentions: Array<Mention>, };
