// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Message } from "./Message";

export type SendMessageResult = { user_message: Message, 
/**
 * Starts out `streaming`.
 */
assistant_message: Message, };
