// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Mention } from "./Mention";
import type { ModelRef } from "./ModelRef";
import type { NewAttachment } from "./NewAttachment";

export type SendMessage = { content: string, 
/**
 * Overrides the default model for this reply.
 */
model: ModelRef | null, 
/**
 * People and events tagged with @, email tagged with #. Each label appears in
 * `content` as `@label` (or `#label` for email).
 */
mentions: Array<Mention>, 
/**
 * Photos sent with the message (at most 10). With photos, `content` may be empty.
 */
attachments: Array<NewAttachment>, 
/**
 * The words came from the microphone (`POST /v1/voice/transcribe`).
 */
spoken: boolean, };
