// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sends an offer's emails, to all of its guests or only these addresses.
 */
export type SendInvitations = { guests: Array<string> | null, };
