// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelRef } from "./ModelRef";

/**
 * User-editable settings. Every field has a default so settings saved by an older
 * version keep loading after new fields are added.
 */
export type Settings = { 
/**
 * What the assistant calls itself.
 */
assistant_name: string, 
/**
 * Model used for new messages. `None` until the user finishes setup.
 */
default_model: ModelRef | null, };
