// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailNotifications } from "./MailNotifications";
import type { MailSorter } from "./MailSorter";
import type { ModelRef } from "./ModelRef";
import type { Permissions } from "./Permissions";
import type { VoiceSettings } from "./VoiceSettings";

/**
 * User-editable settings. Every field has a default so settings saved by an older
 * version keep loading after new fields are added.
 */
export type Settings = { 
/**
 * What the assistant calls itself.
 */
assistant_name: string, 
/**
 * Who the assistant is and how it talks, in the user's own words (Settings ›
 * Personality). Empty means the default voice: helpful, direct and warm. At most
 * [`PERSONALITY_LIMIT`] characters.
 */
personality: string, 
/**
 * Standing instructions the user gives for every conversation ("answer in French
 * unless I write in English"). At most [`INSTRUCTIONS_LIMIT`] characters.
 */
custom_instructions: string, 
/**
 * Model used for new messages. `None` until the user finishes setup.
 */
default_model: ModelRef | null, 
/**
 * Optional model that answers messages with photos (and the message right after)
 * when the default model can't see pictures. `None`: the default answers everything.
 */
photo_model: ModelRef | null, 
/**
 * Whether the assistant learns new things about the user from conversations.
 */
memory_learning: boolean, 
/**
 * The model chosen during setup while it's still downloading. When its download
 * finishes, the daemon makes it the default model, even if no window is open.
 */
pending_model: ModelRef | null, 
/**
 * Whether the first-run welcome has been completed.
 */
onboarding_done: boolean, 
/**
 * Where the welcome was left, so closing the app midway resumes there.
 */
onboarding_step: number, 
/**
 * Whether reminders and routine results also show as notifications on this computer.
 */
desktop_notifications: boolean, 
/**
 * Whether memories are also found by meaning, not only by their words ("my sibling"
 * finds the note about a sister). Needs a small language file on this computer.
 */
memory_semantic: boolean, 
/**
 * Whether new mail is sorted (needs a reply / important / everything else) and
 * summarised in the background by the active model.
 */
mail_sorting: boolean, 
/**
 * What sorts it: the user's own model (the default), or a cloud decision model the
 * user chose.
 */
mail_sorter: MailSorter, 
/**
 * What the assistant may do without asking first.
 */
permissions: Permissions, 
/**
 * Whether this computer asks GitHub, about once a day, if a newer version of Mimi
 * has been published. Off unless the user turns it on.
 */
update_check: boolean, 
/**
 * Talking to the assistant and hearing it (Settings › Voice).
 */
voice: VoiceSettings, 
/**
 * Which new emails show as notifications on this computer (Settings › Reminders &
 * notifications).
 */
mail_notifications: MailNotifications, };
