// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailSorter } from "./MailSorter";
import type { ModelRef } from "./ModelRef";
import type { Permissions } from "./Permissions";

/**
 * User-editable settings. Every field has a default so settings saved by an older
 * version keep loading after new fields are added.
 */
export type Settings = { 
/**
 * What the assistant calls itself.
 */
assistant_name: string, 
/**
 * Model used for new messages. `None` until the user finishes setup.
 */
default_model: ModelRef | null, 
/**
 * Whether the assistant learns new things about the user from conversations.
 */
memory_learning: boolean, 
/**
 * The model chosen during setup while it's still downloading. When its download
 * finishes, the daemon makes it the default model, even if no window is open.
 */
pending_model: ModelRef | null, 
/**
 * Whether the first-run welcome has been completed.
 */
onboarding_done: boolean, 
/**
 * Where the welcome was left, so closing the app midway resumes there.
 */
onboarding_step: number, 
/**
 * Whether reminders and routine results also show as notifications on this computer.
 */
desktop_notifications: boolean, 
/**
 * Whether memories are also found by meaning, not only by their words ("my sibling"
 * finds the note about a sister). Needs a small language file on this computer.
 */
memory_semantic: boolean, 
/**
 * Whether new mail is sorted (needs a reply / important / everything else) and
 * summarised in the background by the active model.
 */
mail_sorting: boolean, 
/**
 * What sorts it: the user's own model (the default), or a cloud decision model the
 * user chose.
 */
mail_sorter: MailSorter, 
/**
 * What the assistant may do without asking first.
 */
permissions: Permissions, };
