// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of `POST /v1/voice/speak`: text to read aloud, one part at a time.
 */
export type SpeakRequest = { 
/**
 * Markdown, as the assistant wrote it; it's turned into what one would say.
 */
text: string, 
/**
 * Which part (0-based): long text is read in parts, so it starts sooner.
 */
part: number, 
/**
 * A voice to use instead of the chosen one (to hear it in Settings).
 */
voice: string | null, };
