// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VoicePack } from "./VoicePack";

/**
 * One part of the text as speech, or the voice it needs still downloading.
 */
export type Speech = { "kind": "audio", 
/**
 * A WAV file, base64-encoded.
 */
audio: string, 
/**
 * How many parts the text has.
 */
parts: number, } | { "kind": "downloading", pack: VoicePack, } | { "kind": "nothing" };
