// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SplitPerson = { 
/**
 * The card's `PersonSource.source_id`: `None` for what the user added by hand.
 */
source_id: string | null, record: string, };
