// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of `POST /v1/google/sign-in`.
 */
export type StartGoogleSignIn = { 
/**
 * Signs an existing Google connection in again (after Google stopped accepting it),
 * keeping its calendars' ids and everything that refers to them.
 */
reconnect: string | null, };
