// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyStorage } from "./KeyStorage";

/**
 * Authenticated daemon status.
 */
export type Status = { version: string, pid: number, uptime_secs: number, data_dir: string, key_storage: KeyStorage, };
