// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of `POST /v1/voice/transcribe`: something the user said.
 */
export type TranscribeRequest = { 
/**
 * The recording, base64-encoded: WAV, Ogg/Opus, WebM, MP4/AAC, MP3 or FLAC.
 */
data: string, };
