// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What was understood.
 */
export type Transcript = { 
/**
 * The words, empty if none were heard.
 */
text: string, 
/**
 * How long the recording was.
 */
duration_ms: number, };
