// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Release } from "./Release";

/**
 * Whether a newer version of Mimi has been published (Settings › General › "Check for new
 * versions", off by default). Checked by asking GitHub, where Mimi is published, directly
 * from this computer.
 */
export type UpdateStatus = { 
/**
 * The version running now.
 */
current: string, 
/**
 * The newest published version, when it's newer than `current`.
 */
available: Release | null, 
/**
 * When GitHub last answered (ms since the epoch).
 */
checked_at: number | null, 
/**
 * Why the last check failed, in plain words.
 */
error: string | null, };
