// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a model can see the photos sent to it (`GET /v1/models/vision`).
 */
export type VisionSupport = { 
/**
 * False also when it can't be told (the model source doesn't say).
 */
sees_images: boolean, };
