// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How voices sound, and what they ask of the computer.
 */
export type VoiceStyle = "natural" | "light";
