// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VoiceInfo } from "./VoiceInfo";
import type { VoicePack } from "./VoicePack";
import type { VoiceStyle } from "./VoiceStyle";

/**
 * What's needed to listen and speak, and how far along it is (`GET /v1/voice`,
 * `VoiceChanged` events).
 */
export type VoiceStatus = { 
/**
 * The recognizer in use: the chosen one, or the one that suits the user's language.
 */
listening: VoicePack, 
/**
 * Every recognizer the user can choose.
 */
recognizers: Array<VoicePack>, 
/**
 * How replies sound now: the chosen style, or the recommended one.
 */
style: VoiceStyle, 
/**
 * What suits this computer.
 */
recommended_style: VoiceStyle, 
/**
 * Every voice, by language, whichever style it is.
 */
voices: Array<VoiceInfo>, 
/**
 * Voice files on this computer or downloading, to show and remove.
 */
packs: Array<VoicePack>, };
