// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackState } from "./PackState";

/**
 * Something Mimi downloads to listen or speak: a speech recognizer, or a set of voices.
 */
export type VoicePack = { id: string, 
/**
 * What it is, in plain words ("Understands 25 European languages").
 */
label: string, 
/**
 * One line more: languages, speed.
 */
detail: string, 
/**
 * Download size.
 */
bytes: number, state: PackState, 
/**
 * While downloading: how much has arrived.
 */
done_bytes: number | null, 
/**
 * Why the last download failed, if it did.
 */
error: string | null, };
