// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VoiceStyle } from "./VoiceStyle";

/**
 * A voice for reading aloud.
 */
export type VoiceInfo = { id: string, 
/**
 * Its name ("Siwis").
 */
name: string, 
/**
 * The language it speaks, as a tag ("fr", "en-US").
 */
language: string, 
/**
 * That language, in English ("French", "English (US)").
 */
language_name: string, style: VoiceStyle, 
/**
 * The pack it comes in (`VoicePack.id`).
 */
pack: string, };
