// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VoiceStyle } from "./VoiceStyle";

/**
 * How the assistant talks and listens (Settings › Voice). Everything happens on this
 * computer: speech is turned into words, and replies into speech, by files Mimi
 * downloads once.
 */
export type VoiceSettings = { 
/**
 * Send what the user said as soon as they stop talking, instead of putting the
 * words in the message box to check first.
 */
send_when_done: boolean, 
/**
 * The speech recognizer that understands the user (a `VoiceStatus.recognizers`
 * id). `None`: the one that suits their language.
 */
recognizer: string | null, 
/**
 * How replies sound when read aloud. `None`: what suits this computer.
 */
style: VoiceStyle | null, 
/**
 * The voice chosen for a language, by the language without its region (`en`, `fr`)
 * → `VoiceInfo.id`. Languages without one get a voice of the chosen style.
 */
voices: { [key in string]: string }, 
/**
 * Reading speed, in percent of normal (75–150).
 */
speed: number, 
/**
 * In messaging apps, answer a voice message with a voice message too, after the
 * written reply (Telegram and Matrix: Signal can't play what Mimi records).
 */
reply_with_voice: boolean, };
