// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single-use link that signs a browser in to the web interface.
 */
export type WebLoginLink = { url: string, };
